- hosts: all
  become: true

  vars:
    other_user_packages:
    - chromium


  roles:
  - { role: common,
        enable_vnc: True }
  - { role: workstation-xfce4,
        include_nm: false }

  tasks:
  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: install other user packages
    apt:
      name: "{{ item }}"
      state: present
    with_items: "{{other_user_packages}}"

  - name: add gstreamer1.0 stuff
    debug:
      msg: 'TODO: add gstreaer'

  - name: add v4l2loopback device
    debug:
      msg: 'TODO: v4l2loopback install'

  - name: run device as service on startup?
    debug:
      msg: 'TODO: run gstreamer command on startup'
