- hosts: all
  become: true

  vars:
    other_user_packages:
    - chromium
    fakeav_repo_path: https://github.com/moozer/fakeav.git

  roles:
  - { role: workstation-xfce4,
        include_nm: false }
  - { role: common,
        enable_vnc: True }

  tasks:
  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: install other user packages
    apt:
      name: "{{ item }}"
      state: present
    with_items: "{{other_user_packages}}"

  - name: v4l2loopback and gstreamer install
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - v4l2loopback-dkmsv4l2loopback-dkms
      - gstreamer1.0-plugins-good
      - gstreamer1.0-tool

#      - gstreamer1.0-plugins-bad
#      - gstreamer1.0-plugins-ugly

  - name: add v4l2loopback module to kernel
    modprobe:
      name: v4l2loopback
      state: present


  - name: "pull fakeav repo from {{ fakeav_repo_path }}"
    git:
      repo: "{{ fakeav_repo_path }}"
      dest: /opt/fakeav

#      accept_hostkey: no


  - name: run device as service on startup?
    debug:
      msg: 'TODO: run gstreamer command on startup'
